name: vip_tuts
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  - pandas=2.2.1
  - pip=23.3.1
  - nltk=3.9.1
  - jupyter=1.0.0
  - jupyter_client=7.4.9
  - jupyter_console=6.6.3
  - jupyter_core=5.3.0
  - jupyter_events=0.6.3
  - jupyter_server=1.23.4
  - jupyter_server_fileid=0.9.0
  - jupyter_server_ydoc=0.8.0
  - jupyter_ydoc=0.2.4
  - jupyterlab=3.6.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.22.0
  - jupyterlab_widgets=3.0.5
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - scikit-learn=1.4.2
  - numpy=1.26.4
  - numpy-base=1.26.4
  - ipykernel=6.25.0
  - ipython=8.15.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - tqdm=4.65.2
  - scikit-learn=1.4.2
  - opencv=4.9.0
  - seaborn=0.12.2
  - spacy=3.7.4
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.5
  - portalocker=3.0.0
  - transformers=4.32.1
  - accelerate=0.30.1

      
      